### ISSUE TITLE
TacacsClient cannot specify unencrypted flag.

### ISSUE THREAD

**Issue by imecimore** [janicki/TACACS#2]
When creating a client, there's no way to specify to set the TAC_PLUS.PACKET.FLAG.UNENCRYPTED flag.  Even if this shouldn't be used in production, I think some clients may want to authenticate with a server using the unencrypted flag to enable easier debugging between client and server interactions.

**Comment by janicki** [comment]
Thanks for the feedback!  You make a good point.  I'll poke my head back into this project in the next few weeks and take care of that.  I hope the code is useful to you.  I'd love to hear what you're working on, if you can.  

Thanks,
Chris

**Comment by imecimore** [comment]
I'm not sure if I can share what I'm working on, but I really like this project.  It's much nicer than any other TACACS project I've found and it's better than starting from scratch.

I went ahead and sent you a PR.  I tried to stick with your coding style.  Let me know if there is any testing you would like performed.
