### ISSUE TITLE
exampleAuthenPAP does not work

### ISSUE THREAD

**Issue by ceprateek** [janicki/TACACS#8]
public static void main(String[] args) throws IOException, TimeoutException
	{
		if (args.length==0) { System.out.println("java -jar tacacs.jar <host> <key>"); }
		else
		{
			String host = args.length>0 ? args[0] : null;
			String key = "<hardcode>";
			TacacsClient tc = new TacacsClient(host, key);

			// substitute another example here for testing
			exampleAuthenPAP(args, tc);
			// If you run another command, first check tc.isStillConnected().
			tc.shutdown();
		}
	}

The exampleAuthenPAP says login failed for a valid user credential.

**Comment by AugurSystems** [comment]
Hi.  I don't *think* anything changed that would have broken PAP login.  Could you please verify that the 'host' and 'key' that were used in your test are also correct?

**Comment by ceprateek** [comment]
Hi, Thanks for taking the time for the response.

The server details are correct, I was wondering if the users are defined in the server as they should be. I have defined users in tac_plus.conf as follows:
user = admin {
     login = cleartext Cisco123!
     member = vtsadministrator
}

Is this an issue you see for PAP login ?

Thanks
Prateek

**Comment by janicki** [comment]
I'm not personally familiar with tac_plus.conf, but I found a page that describes the file: [http://manpages.ubuntu.com/manpages/trusty/man5/tac_plus.conf.5.html](url)  I copied the description of the user attributes below.  Notice the 'pap' and 'opap' properties.
```
                  user = bart {
                      arap = cleartext "arap password"
                      chap = cleartext "chap password"
                      enable = <password_spec>
                      pap  = cleartext "inbound pap password"
                      opap = cleartext "outbound pap password"
                      pap  = des <des_string>
                      pap  = file <filename>
                      pap  = PAM
                      login = <password_spec>
                      global = cleartext "outbound pap password"
                  }
```
However, this is beyond the scope of our TACACS+ Java library.  You may need to find another source for help with your server's config, sorry.  We didn't test our library against the Tac_plus implementation of TACACS+, so we have no experience configuring that server.

**Comment by ceprateek** [comment]
Hi,

This definitely helped and I was able to use the server for PAP.
For documentation purpose I defined the user as:
user = operator {
        login = cleartext operator123
	pap  = cleartext "operator123"
}

**Comment by janicki** [comment]
I'm glad you figured it out!  Thanks for reporting the result, and good luck with your project.
